// $(document).ready(function(){
//   $('#wgDiv').hover(function(){
//     $('#watergate').fadeIn(1200).show();
//   });
//   $('#bbDiv').hover(function(){
//     $('#baseball').fadeIn(1200).show();
//   });
//   $('#bsDiv').hover(function(){
//     $('#bigSur').fadeIn(1200).show();
//   });
//   $('#agDiv').hover(function(){
//     $('#adam').fadeIn(1200).show();
//   });
//   $('#mcDiv').hover(function(){
//     $('#mccabes').fadeIn(1200).show();
//   });
// })
